# Standalone demographics listing: creates simulated data, Excel, and clinical RTF.
set.seed(4201)

arg <- grep("^--file=", commandArgs(), value = TRUE)
out_dir <- if (length(arg)) dirname(normalizePath(gsub("~[+]~", " ", sub("^--file=", "", arg[1])), mustWork = TRUE)) else getwd()
stem <- "01_demographics_listing"

# Source-style records; CSG has been replaced by PILOT.
original <- data.frame(
  USUBJID = sprintf("PILOT-%04d", 1001:1014),
  TRT01P = c("Arm A","Arm A","Arm A","Arm B","Arm A","Arm B","Arm A","Arm B","Arm B","Arm B","Arm A","Arm B","Arm B","Arm A"),
  TRT01PN = c(1,1,1,2,1,2,1,2,2,2,1,2,2,1),
  SITEID = c("002",rep("003",4),rep("004",5),rep("007",4)),
  SITENAM = c("Site 002",rep("Site 003",4),rep("Site 004",5),rep("Site 007",4)),
  AGE = c(48,63,35,65,76,72,42,81,67,85,69,35,64,63),
  SEX = c("F","M","F","M","M","F","F","M","M","M","F","F","M","M"),
  ARACE = c("BLACK OR AFRICAN AMERICAN",rep("WHITE",13)),
  WEIGHTBL = c(65.7,99,71.1,99.6,76,62,67.5,55,90.5,74,71.6,56.7,58,70.3),
  HEIGHTBL = c(162,170,168,186,178,157,166,160,165,160,155,174,168,175),
  RANDFL = "Y", stringsAsFactors = FALSE
)

# Simulate twice the original sample while preserving the clinical-data structure.
adsl <- rbind(original, transform(original,
  USUBJID = sprintf("PILOT-%04d", 2001:2014),
  AGE = pmax(18, pmin(90, AGE + sample(-3:3, 14, TRUE))),
  WEIGHTBL = round(WEIGHTBL + rnorm(14, 0, 2), 1)
))
adsl$BMI <- round(adsl$WEIGHTBL / (adsl$HEIGHTBL / 100)^2, 1)
stopifnot(nrow(adsl) == 28, all(names(adsl) == toupper(names(adsl))))

# Locate LibreOffice without requiring the user to add `soffice` to PATH.
find_soffice <- function() {
  candidates <- c(
    Sys.which("soffice"),
    "/Applications/LibreOffice.app/Contents/MacOS/soffice",
    "/Applications/OpenOffice.app/Contents/MacOS/soffice",
    "/Users/dianhe/.cache/codex-runtimes/codex-primary-runtime/dependencies/bin/override/soffice"
  )
  candidates <- candidates[nzchar(candidates) & file.exists(candidates)]
  if (!length(candidates)) {
    stop("LibreOffice was not found. Install LibreOffice or add soffice to PATH before running this program.")
  }
  candidates[1]
}

# Write a standards-compliant XLSX through LibreOffice.
write_xlsx <- function(data, path) {
  csv <- tempfile(fileext = ".csv")
  write.csv(data, csv, row.names = FALSE, na = "", fileEncoding = "UTF-8")
  converted <- file.path(tempdir(), sub("\\.csv$", ".xlsx", basename(csv)))
  if (file.exists(converted)) unlink(converted)
  soffice <- find_soffice()
  ok <- system2(soffice, c("--headless", "--convert-to", "xlsx", "--outdir", shQuote(tempdir()), shQuote(csv)))
  if (ok != 0 || !file.exists(converted)) stop("Unable to create Excel workbook.")
  if (file.exists(path)) unlink(path)
  if (!file.rename(converted, path)) stop("Unable to save Excel workbook.")
  unlink(csv)
}

escape_rtf <- function(x) {
  x <- gsub("\\\\", "\\\\\\\\", as.character(x))
  gsub("([{}])", "\\\\\\1", x)
}

# RTF uses integer cell boundaries. This prevents decimal boundary values from
# appearing as unwanted text in the first column.
write_listing_rtf <- function(data, title, path) {
  con <- file(path, "wb"); on.exit(close(con), add = TRUE)
  w <- function(...) writeLines(paste0(...), con, useBytes = TRUE)
  w("{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Arial;}}\\landscape\\paperw15840\\paperh12240\\margl600\\margr600\\margt500\\margb600")
  w("\\pard\\f0\\fs15 PILOT\\tab Confidential\\tab Page {\\field{\\*\\fldinst PAGE}} of {\\field{\\*\\fldinst NUMPAGES}}\\par")
  w("\\pard\\qc\\b\\fs19 ", escape_rtf(title), "\\b0\\par\\pard\\qc\\fs15 Randomized Population\\par\\par")
  n <- ncol(data)
  # Fill the complete landscape text area and size columns by their content.
  widths <- c(1700, 1700, 900, 2800, 1100, 700, 2400, 1100, 1100, 1140)
  stopifnot(length(widths) == n, sum(widths) == 14640)
  ends <- cumsum(widths)
  for (i in 0:nrow(data)) {
    values <- if (i == 0) names(data) else as.character(data[i, ])
    border <- if (i == 0) "\\clbrdrt\\brdrs\\brdrw15\\clbrdrb\\brdrs\\brdrw15" else if (i == nrow(data)) "\\clbrdrb\\brdrs\\brdrw15" else ""
    w("\\trowd\\trleft0\\trgaph60", if (i == 0) "\\trhdr" else "", paste0(border, "\\cellx", ends, collapse = ""))
    for (j in seq_len(n)) w("\\intbl", if (j <= 4) "\\ql" else "\\qc", if (i == 0) "\\b" else "\\b0", "\\fs15 ", escape_rtf(values[j]), "\\cell")
    w("\\row")
  }
  w("\\pard\\ql\\fs12\\par Source: simulated data generated by this standalone program.\\par}")
}

listing <- adsl[, c("USUBJID","TRT01P","SITEID","SITENAM","AGE","SEX","ARACE","WEIGHTBL","HEIGHTBL","BMI")]
names(listing) <- c("Subject","Treatment","Site","Site Name","Age (Years)","Sex","Race","Weight (kg)","Height (cm)","BMI (kg/m2)")

write_xlsx(adsl, file.path(out_dir, paste0(stem, "_simulated_data.xlsx")))
write_listing_rtf(listing, "Listing 1. Demographics", file.path(out_dir, paste0(stem, ".rtf")))
message("Created ", stem, ": original N=14; simulated N=28")
