# Listing 1: Medical History
# Standalone program rebuilt from the ADMH data structure in the source document.

set.seed(4501)

arg <- grep("^--file=", commandArgs(), value=TRUE)
out_dir <- if (length(arg)) dirname(normalizePath(gsub("~[+]~", " ", sub("^--file=", "", arg[1])), mustWork=TRUE)) else getwd()
stem <- "01_medical_history_listing"

# Build 20 source-style subjects, twice the 10-subject example, using PILOT IDs.
n_original <- 10L
adsl <- data.frame(
  USUBJID=sprintf("PILOT-%04d",1001:(1000+2*n_original)),
  TRT01P=rep(c("Arm A","Arm B"),each=n_original),
  TRT01PN=rep(1:2,each=n_original),
  SITEID=sample(c("002","003","004","007"),2*n_original,TRUE),
  AGE=sample(45:85,2*n_original,TRUE),
  SEX=sample(c("F","M"),2*n_original,TRUE),
  ARACE=sample(c("WHITE","ASIAN","BLACK OR AFRICAN AMERICAN"),2*n_original,TRUE),
  stringsAsFactors=FALSE
)

# Generate medical-history records based on the source document's terminology.
terms <- c("Menopausal symptoms","Cholecystectomy","Hyperuricaemia","Liver disorder","Benign prostatic hyperplasia","Spinal osteoarthritis","Pulmonary embolism","Renal cyst","Cholelithiasis","Urinary incontinence")
soc <- c("Reproductive system and breast disorders","Surgical and medical procedures","Metabolism and nutrition disorders","Hepatobiliary disorders","Reproductive system and breast disorders","Musculoskeletal and connective tissue disorders","Respiratory, thoracic and mediastinal disorders","Renal and urinary disorders","Hepatobiliary disorders","Renal and urinary disorders")
admh <- do.call(rbind,lapply(seq_len(nrow(adsl)),function(i){
  k <- sample(1:3,1); ix <- sample(seq_along(terms),k)
  data.frame(USUBJID=adsl$USUBJID[i],MHSTDTC=as.character(as.Date("2000-01-01")+sample(0:5500,k)),MHENDTC="",MHCURMED=sample(c("Y","N"),k,TRUE),MHENRTPT=sample(c("ONGOING","BEFORE"),k,TRUE),MHTERM=terms[ix],MHDECOD=terms[ix],MHBODSYS=soc[ix],TRT01P=adsl$TRT01P[i],TRT01PN=adsl$TRT01PN[i],SITEID=adsl$SITEID[i],AGE=adsl$AGE[i],SEX=adsl$SEX[i],ARACE=adsl$ARACE[i],stringsAsFactors=FALSE)
}))
stopifnot(nrow(adsl)==20,all(names(admh)==toupper(names(admh))))

# Helper functions for Excel and clinical RTF output are inserted below.
# Locate LibreOffice without requiring `soffice` to be on PATH.
find_soffice <- function() {
  paths <- c(Sys.which("soffice"), "/Applications/LibreOffice.app/Contents/MacOS/soffice", "/Applications/OpenOffice.app/Contents/MacOS/soffice", "/Users/dianhe/.cache/codex-runtimes/codex-primary-runtime/dependencies/bin/override/soffice")
  paths <- paths[nzchar(paths) & file.exists(paths)]
  if (!length(paths)) stop("LibreOffice was not found.")
  paths[1]
}

# Export standards-compliant XLSX data.
write_xlsx <- function(data, path) {
  csv <- tempfile(fileext=".csv")
  write.csv(data, csv, row.names=FALSE, na="", fileEncoding="UTF-8")
  xlsx <- file.path(tempdir(), sub("\\.csv$", ".xlsx", basename(csv)))
  if (file.exists(xlsx)) unlink(xlsx)
  status <- system2(find_soffice(), c("--headless", "--convert-to", "xlsx", "--outdir", shQuote(tempdir()), shQuote(csv)))
  if (status != 0 || !file.exists(xlsx)) stop("Unable to create Excel workbook.")
  if (file.exists(path)) unlink(path)
  if (!file.rename(xlsx, path)) stop("Unable to save Excel workbook.")
  unlink(csv)
}

# Create the clinical RTF listing using integer cell boundaries.
escape_rtf <- function(x) { x <- gsub("\\\\", "\\\\\\\\", as.character(x)); gsub("([{}])", "\\\\\\1", x) }
write_rtf <- function(data, path) {
  con <- file(path, "wb"); on.exit(close(con), add=TRUE)
  w <- function(...) writeLines(paste0(...), con, useBytes=TRUE)
  w("{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Arial;}}\\landscape\\paperw15840\\paperh12240\\margl600\\margr600\\margt500\\margb600")
  w("\\pard\\fs15 PILOT\\tab Confidential\\tab Page {\\field{\\*\\fldinst PAGE}}\\par\\pard\\qc\\b\\fs19 Listing 1. Medical History\\b0\\par\\pard\\qc\\fs15 Safety Population\\par\\par")
  n <- ncol(data)
  widths <- c(1500, 1500, 2700, 2200, 1200, 1400, 1200, 1200, 870, 870)
  stopifnot(length(widths) == n, sum(widths) == 14640)
  ends <- cumsum(widths)
  for (i in 0:nrow(data)) { v <- if(i==0) names(data) else as.character(data[i,]); b <- if(i==0) "\\clbrdrt\\brdrs\\brdrw15\\clbrdrb\\brdrs\\brdrw15" else if(i==nrow(data)) "\\clbrdrb\\brdrs\\brdrw15" else ""; w("\\trowd\\trleft0\\trgaph60",if(i==0)"\\trhdr" else "",paste0(b,"\\cellx",ends,collapse="")); for(j in seq_len(n)) w("\\intbl",if(j<=3)"\\ql" else "\\qc",if(i==0)"\\b" else "\\b0","\\fs14 ",escape_rtf(v[j]),"\\cell"); w("\\row") }
  w("\\pard\\ql\\fs12\\par Source: simulated data generated by this standalone program.\\par}")
}

listing <- admh[order(admh$USUBJID,admh$MHBODSYS,admh$MHDECOD),c("USUBJID","TRT01P","MHBODSYS","MHDECOD","MHENRTPT","MHCURMED","MHSTDTC","MHENDTC","AGE","SEX")]
names(listing) <- c("Subject","Treatment","System Organ Class","Medical History Term","Time Period","Current Medication","Start Date","End Date","Age","Sex")
write_xlsx(admh,file.path(out_dir,paste0(stem,"_simulated_data.xlsx")))
write_rtf(listing,file.path(out_dir,paste0(stem,".rtf")))
message("Created ",stem,": original N=10; simulated N=20")
