---
title: "Fit regression model from a fan-shaped relation"
output: html_document
date: '2023-10-30'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Data and plot
```{r}
x = (runif(5000))
y = x*(1+rnorm(5000,0,0.1))
plot(x,y,cex=.5,pch=21)

```

```{r}
mod=lm(y~x)
summary(mod)
plot(mod)
```

### Examine standard deviation
```{r}
x_cat=cut(x, breaks = 20)
x_squa=(x)^2
data=data.frame(x,y,x_cat,x_squa)
sd=aggregate(data$y, list(data$x_cat), FUN=sd) 
barplot((sd$x))
```

### Method1, construct a weighted regression using weights proportional to 1/x^2
```{r}
mod2=lm(y~x,weights=1/x_squa,data=data)
plot(mod2)
summary(mod2)
```


### Mothod2, Take logs, and fit a linear model with the coefficient restricted to 1 (also called an offset)
```{r}
log_y=log(y)
log_x=log(x)
plot(x,log_y,cex=.5,pch=21)
plot(log_x,log_y,cex=.5,pch=21)


```

```{r}
mod3=lm(log_y~(-1+log_x))
plot(mod3)
summary(mod3)
```

### Method3, fit a gamma glm with identity link (and perhaps without an intercept)
```{r}
# mod4=glm(y~-1+x,family=Gamma)
# plot(mod4)
# summary(mod4)
```

### References   
[https://stats.stackexchange.com/questions/156654/fit-regression-model-from-a-fan-shaped-relation-in-r]
[https://www.itl.nist.gov/div898/handbook/pri/section2/pri24.htm]


