# Standalone vital-signs analysis generated from DOCX code segment 3.

suppressPackageStartupMessages({library(dplyr);library(tidyr)})
set.seed(20260828)
arg <- grep("^--file=", commandArgs(FALSE), value=TRUE)
script_raw <- if(length(arg)) sub("^--file=", "", arg[1]) else "."
script_path <- normalizePath(gsub("~\\+~", " ", script_raw))
out_dir <- if(file.info(script_path)$isdir) script_path else dirname(script_path)
stem <- tools::file_path_sans_ext(basename(script_path))

b64decode <- function(s){a<-strsplit(gsub("\\s","",s),"")[[1]];tab<-c(LETTERS,letters,0:9,"+","/");v<-match(a,tab)-1L;v[is.na(v)]<-0L;bits<-as.integer(unlist(lapply(v,function(x)intToBits(x)[6:1])));n<-floor(length(bits)/8);as.raw(vapply(seq_len(n),function(i)sum(bits[((i-1)*8+1):(i*8)]*2^(7:0)),numeric(1)))}
unpack_csv <- function(s) read.csv(text=rawToChar(memDecompress(base64enc::base64decode(s),type="gzip")),stringsAsFactors=FALSE,check.names=FALSE,na.strings=c("NA",""))

xml_escape <- function(x){x[is.na(x)]<-"";x<-gsub("&","&amp;",x,fixed=TRUE);x<-gsub("<","&lt;",x,fixed=TRUE);x<-gsub(">","&gt;",x,fixed=TRUE);gsub('"',"&quot;",x,fixed=TRUE)}
excel_col <- function(n){z<-character(length(n));for(j in seq_along(n)){k<-n[j];s<-"";while(k>0){k<-k-1;s<-paste0(intToUtf8(65+k%%26),s);k<-k%/%26};z[j]<-s};z}
write_xlsx <- function(sheets,path){
 sheets<-lapply(sheets,function(d){names(d)<-toupper(names(d));d});sn<-substr(gsub("[^A-Za-z0-9_]","_",names(sheets)),1,31);td<-tempfile("xlsx_");dir.create(td);for(z in c("_rels","docProps","xl","xl/_rels","xl/worksheets"))dir.create(file.path(td,z),recursive=TRUE,showWarnings=FALSE)
 types<-paste0('<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>',paste0('<Override PartName="/xl/worksheets/sheet',seq_along(sheets),'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>',collapse=""),'<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/></Types>');writeLines(types,file.path(td,"[Content_Types].xml"))
 writeLines('<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>',file.path(td,"_rels/.rels"))
 sh<-paste0('<sheet name="',sn,'" sheetId="',seq_along(sn),'" r:id="rId',seq_along(sn),'"/>',collapse="");writeLines(paste0('<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>',sh,'</sheets></workbook>'),file.path(td,"xl/workbook.xml"));rels<-paste0('<Relationship Id="rId',seq_along(sn),'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet',seq_along(sn),'.xml"/>',collapse="");writeLines(paste0('<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">',rels,'<Relationship Id="rId',length(sn)+1,'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'),file.path(td,"xl/_rels/workbook.xml.rels"))
 writeLines('<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="10"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="10"/><name val="Arial"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF1F4E78"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="2"><xf xfId="0" fontId="0" fillId="0"/><xf xfId="0" fontId="1" fillId="1" applyFont="1" applyFill="1"/></cellXfs></styleSheet>',file.path(td,"xl/styles.xml"))
 for(k in seq_along(sheets)){d<-sheets[[k]];a<-rbind(names(d),as.matrix(d));rows<-vapply(seq_len(nrow(a)),function(i){cc<-vapply(seq_len(ncol(a)),function(j){v<-as.character(a[i,j]);if(i>1&&is.numeric(d[[j]])&&!is.na(d[i-1,j]))sprintf('<c r="%s%d"><v>%s</v></c>',excel_col(j),i,d[i-1,j])else sprintf('<c r="%s%d" t="inlineStr" s="%d"><is><t>%s</t></is></c>',excel_col(j),i,ifelse(i==1,1,0),xml_escape(v))},character(1));sprintf('<row r="%d">%s</row>',i,paste0(cc,collapse=""))},character(1));writeLines(paste0('<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView showGridLines="0" workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetData>',paste0(rows,collapse=""),'</sheetData></worksheet>'),file.path(td,"xl/worksheets",paste0("sheet",k,".xml")))}
 writeLines('<?xml version="1.0" encoding="UTF-8"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:creator>PILOT</dc:creator></cp:coreProperties>',file.path(td,"docProps/core.xml"));writeLines('<?xml version="1.0" encoding="UTF-8"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"><Application>R</Application></Properties>',file.path(td,"docProps/app.xml"));old<-setwd(td);on.exit(setwd(old),add=TRUE);if(file.exists(path))unlink(path);utils::zip(path,list.files(".",recursive=TRUE,all.files=TRUE,no..=TRUE),flags="-q")
}

rtf_escape<-function(x){x<-gsub("\\\\","\\\\\\\\",as.character(x));gsub("([{}])","\\\\\\1",x)}
write_rtf<-function(tab,title,path,foot){tab<-as.data.frame(tab,check.names=FALSE);tab[]<-lapply(tab,as.character);con<-file(path,"wb");on.exit(close(con));w<-function(...)writeLines(paste0(...),con,useBytes=TRUE);w("{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Arial;}}\\landscape\\paperw15840\\paperh12240\\margl600\\margr600\\margt500\\margb600");w("\\pard\\f0\\fs15 PILOT\\tab Confidential\\tab Page {\\field{\\*\\fldinst PAGE}} of {\\field{\\*\\fldinst NUMPAGES}}\\par");w("\\pard\\qc\\b\\fs19 ",rtf_escape(title),"\\b0\\par\\pard\\qc\\fs15 Safety Population\\par\\par");n<-ncol(tab);first<-if(n>=6)2700 else 3600;ends<-cumsum(c(first,rep((14640-first)/(n-1),n-1)));for(i in 0:nrow(tab)){vals<-if(i==0)names(tab)else unlist(tab[i,],use.names=FALSE);bd<-if(i==0)"\\clbrdrt\\brdrs\\brdrw15\\clbrdrb\\brdrs\\brdrw15"else if(i==nrow(tab))"\\clbrdrb\\brdrs\\brdrw15"else"";w("\\trowd\\trgaph55",if(i==0)"\\trhdr"else"",paste0(bd,"\\cellx",round(ends),collapse=""));for(j in seq_len(n))w("\\intbl",if(j<=2)"\\ql"else"\\qc",if(i==0)"\\b"else"\\b0","\\f0\\fs13 ",rtf_escape(vals[j]),"\\cell");w("\\row")};w("\\pard\\ql\\fs12\\par ",rtf_escape(foot),"\\par Source: simulated data generated by this standalone program. Generated: ",format(Sys.Date(),"%d%b%Y"),"\\par}")}

simulate_profiles<-function(adsl,advs,original_n){
 trts<-sort(unique(adsl$TRT01AN));new_adsl<-list();new_advs<-list();next_id<-1L
 for(trt in trts){n_src<-sum(adsl$TRT01AN==trt);n_new<-2L*n_src;src_ids<-unique(advs$USUBJID[advs$TRT01AN==trt]);if(length(src_ids)==0)src_ids<-unique(advs$USUBJID);picked<-sample(src_ids,n_new,replace=TRUE)
  for(k in seq_len(n_new)){prof<-advs[advs$USUBJID==picked[k]&advs$TRT01AN==trt,,drop=FALSE];if(!nrow(prof))prof<-advs[advs$USUBJID==picked[k],,drop=FALSE];id<-sprintf("PILOT-%04d",next_id);next_id<-next_id+1L;prof$USUBJID<-id;if("AVAL"%in%names(prof)){sdv<-ave(advs$AVAL,advs$PARAMCD,FUN=function(x)max(sd(x,na.rm=TRUE),1));prof$AVAL<-round(prof$AVAL+rnorm(nrow(prof),0,0.04*sdv[match(prof$PARAMCD,advs$PARAMCD)]),1)};new_advs[[length(new_advs)+1]]<-prof;new_adsl[[length(new_adsl)+1]]<-data.frame(USUBJID=id,TRT01AN=trt,SAFFL="Y",stringsAsFactors=FALSE)}
 }
 a<-bind_rows(new_adsl);v<-bind_rows(new_advs);if("BASE"%in%names(v)){base_tbl<-v%>%group_by(USUBJID,PARAMCD)%>%arrange(AVISITN,.by_group=TRUE)%>%summarise(BASE=first(AVAL),.groups="drop");v<-v%>%select(-any_of(c("BASE","CHG")))%>%left_join(base_tbl,by=c("USUBJID","PARAMCD"))%>%mutate(CHG=AVAL-BASE)};list(ADSL=a,ADVS=v)
}

EMBED_ADSL<-"H4sIAJ+qkWoC/wsNDnXy8nTRCQkKMTB09NMJdnRz8+EK8PTxD9EN9g8NcnbVMdSJRBUwIihgSLoKQ9LNAAkAAGtn9InAAAAA"
EMBED_ADVS<-"H4sIAJ+qkWoC/+Wc227TQBCG73kKX4JkYHftPVgCpPSACColilOQLwsEqKAEJeWCt8c51DNbgYS9452V2qKYpFHn89rT+TXzZy/qi6PX05N8NplP3pzvD8eHp/nk3bSeLs4Px/YwOcuPJvVpfjyfLuTuUe0ei/0rL8/2rx2ORXusJy/bx8V8IeTk/MFsevZ28bh+ezE/Ps1lXjf10Syvf29uVt+vPmZH31erT9lsvdxsfq2X2cPr61dfHrVve79cfstkLssql4V6YvZfNn/xPJNW3L7v2fOs6p5Mf3xcLy83y2z1OWvfprofnO++m1wOYlF7FtVySG6Wcs9SthzmSXH44oYyeyjTcmhuFrdncblUiptFisNdLLY0QDIWlspPppMW6+Tq8v+Sy+lbjhbEuB2LxCyl/geL1JilGc7SJZetaFgC1qVLLqvZWbqcalmKLtF5WLqcMo6dBeWUGW9linx+Ws/y+XLz82p9ebNa/87mlzctxIf219x83Ty9vvqBi1T7p2+XydsU/fDzehdd3v7/TnB9eDkoNNQkGzs0lKDoZw2FJvpZQ12Jfta4jBAG763EColLmAD5EVLCVKgkq7AMYoWCxCgFNwtkirbEV60ZDAU5lNCthLMrBlZ/kYaLrvckpOCpQLnmVEJUXeYltVZdDlaCnaVLPU9OclOh3HPjrVFfMee2/wbWWBUm5qKHhpoVPTSUKBM7NBSi6Gd9R8xRBe/fVlNINynHq+EEKrssLJAGquBeF9RNY2dBis1ys+DMKR0NTUOgz7yKaotE9JnXquGmgsaaYGeBxho/C2qssbP4Wmwsmr5azPJpMcOnxey91GLmvmoxZTz9Q9N2CJ11KpkMFCSGTGelIGXuiBGaDlvo9FMWxFBEY9AIF7C3gjMGj/sEx1gLdJtgIuiSLIHV6HLLBa1GQzHyxEKIZzXwyHO8azNg5FkyjTx17NDeyLNkGnmWsUNDMYm+4LhkOLrgvZWZqBJojvH3xBR3fw73xNhbYdJyLwdOD6lHa8z1F1LYN2VVIq0waxKiglZYSlR/d5txU4EIK9lZUMp5TsWxuPrbwJRg6laZ2KGxDSxyaHQbKDkgeEM1vvNsT1Ua9njfalSl4ZMvRTIrhUxZ6Vw+1H+VxFANScuoiHBXDTFlQQ3Q+Amrh96ws0AbqUKFkYSKxE1vqakomkyeiOBeK6x0JPVdTtB4cgE1P6zx1MYdXvFlqD0r8llDsYoeGtuzIof2G09kwXvrO701uRSJTALxKIkXCvJBpwOFZF06UEjWUUPRyDqLJ4GhWE1YIQZZJ3JH5XwJFXMJsHTpVvGzgJseN864qbo080C4qVCejXjl+go3zTcxLPkmhsW9nBiWnBPDgnFi6FdbydlEQVbGdKCQl0vQsFAIN+OSWSDIIV8hBUI1ZMJNU99MFP24Sm/1Emfvzf/oIbOFC/dtHLOFi39dQKRpJgIsyMa7NgPM9YZJkLnYoaHuVLFDd6mg5IDQ//jD3VeQRT/rOxYuwyXI7FZmGJriGerlcthTzwuFxvc6nIVsswpPh7FCoQYaNVRDYvwyYrQl6i2/pBAJbU3hVdhUtqZIYBMIaKGltE2Gp84S2pCiiLBGMWefim/2qUIVG5vBLPqC08w+FefsM9jb1pZZYTk3qkKNY2x954VCljaXDBSSbpKbBXWfHTeLt1kF3jpjJKz+u1YoJJLKiqC8NRRW/SIhKrDq24SooLGGTWPcVGBl42fxDGyj0fSVbtvP+TPtZBE9NJQqMSh0QyHdop81+oRY7NDeB8KCgv8BI9kC8BtgAAA="
ORIGINAL_N<-10L

simulate_profiles<-function(adsl,advs,original_n){trts<-sort(unique(adsl$TRT01AN));a<-list();v<-list();idn<-1L;for(trt in trts){n_new<-2L*sum(adsl$TRT01AN==trt);template<-advs%>%filter(TRT01AN==trt)%>%group_by(PARAMN,PARAMCD,PARAM,AVISITN,AVISIT)%>%slice_sample(n=1)%>%ungroup();for(k in seq_len(n_new)){id<-sprintf("PILOT-%04d",idn);idn<-idn+1L;x<-template;x$USUBJID<-id;x$AVAL<-round(x$AVAL+rnorm(nrow(x),0,pmax(abs(x$AVAL)*.03,.5)),1);a[[length(a)+1]]<-data.frame(USUBJID=id,TRT01AN=trt,SAFFL="Y");v[[length(v)+1]]<-x}};list(ADSL=bind_rows(a),ADVS=bind_rows(v))}
make_output<-function(adsl,advs){a<-adsl;v<-advs;tot<-a%>%count(TRT01AN,name="N");labs<-setNames(paste0(ifelse(tot$TRT01AN==1,"Placebo","Active")," (N=",tot$N,")"),tot$TRT01AN);labs<-c(labs,Total=paste0("Total (N=",n_distinct(a$USUBJID),")"));v<-bind_rows(v%>%mutate(TREATMENT=as.character(TRT01AN)),v%>%mutate(TREATMENT="Total"));st<-bind_rows(v%>%filter(CRIT1!="")%>%transmute(USUBJID,PARAMN,PARAMCD,PARAM,TREATMENT,CRITERIAN=1,CRITERIA=CRIT1,FLAG=CRIT1FL),v%>%filter(CRIT2!="")%>%transmute(USUBJID,PARAMN,PARAMCD,PARAM,TREATMENT,CRITERIAN=2,CRITERIA=CRIT2,FLAG=CRIT2FL),v%>%filter(CRIT3!="")%>%transmute(USUBJID,PARAMN,PARAMCD,PARAM,TREATMENT,CRITERIAN=3,CRITERIA=CRIT3,FLAG=CRIT3FL));s<-st%>%group_by(PARAMN,PARAM,CRITERIAN,CRITERIA,TREATMENT)%>%summarise(N=n_distinct(USUBJID[FLAG=="Y"]),M=n_distinct(USUBJID[FLAG%in%c("Y","N")]),.groups="drop")%>%mutate(VALUE=ifelse(M>0,sprintf("%d/%d (%.1f%%)",N,M,100*N/M),"0/0"))%>%select(PARAMN,PARAM,CRITERIAN,CRITERIA,TREATMENT,VALUE)%>%pivot_wider(names_from=TREATMENT,values_from=VALUE,values_fill="0/0");names(s)[names(s)=="1"]<-labs["1"];names(s)[names(s)=="2"]<-labs["2"];names(s)[names(s)=="Total"]<-labs["Total"];s%>%arrange(PARAMN,CRITERIAN)%>%mutate(PARAMETER_DISPLAY=if_else(row_number()==1L|PARAM!=lag(PARAM),PARAM,""))%>%select(Parameter=PARAMETER_DISPLAY,Criteria=CRITERIA,all_of(unname(labs)))}
TITLE<-"Table 3. Subjects Meeting Potentially Clinically Significant Vital Sign Criteria"
FOOT<-"Values are n/m (%), where n is the number of subjects meeting the criterion and m is the number with an evaluable result."

adsl<-unpack_csv(EMBED_ADSL);advs<-unpack_csv(EMBED_ADVS)
original_n<-ORIGINAL_N
sim<-simulate_profiles(adsl,advs,original_n)
names(sim$ADSL)<-toupper(names(sim$ADSL));names(sim$ADVS)<-toupper(names(sim$ADVS))
stopifnot(n_distinct(sim$ADSL$USUBJID)==2L*original_n,all(names(sim$ADSL)==toupper(names(sim$ADSL))),all(names(sim$ADVS)==toupper(names(sim$ADVS))))
write_xlsx(sim,file.path(out_dir,paste0(stem,"_simulated_data.xlsx")))
output<-make_output(sim$ADSL,sim$ADVS)
write_rtf(output,TITLE,file.path(out_dir,paste0(stem,".rtf")),FOOT)
message(sprintf("Created %s: original N=%d; simulated N=%d",stem,original_n,n_distinct(sim$ADSL$USUBJID)))
