# Listing 1: Physical Examination
# Standalone program rebuilt from the ADPE structure in the source document.

set.seed(4601)

arg <- grep("^--file=", commandArgs(), value=TRUE)
out_dir <- if (length(arg)) dirname(normalizePath(gsub("~[+]~", " ", sub("^--file=", "", arg[1])), mustWork=TRUE)) else getwd()
stem <- "01_physical_examination_listing"

# Create 20 subjects (twice the 10-subject source-style population).
n_original <- 10L
subjects <- sprintf("PILOT-%04d", 1001:(1000 + 2*n_original))
adsl <- data.frame(USUBJID=subjects,AGE=sample(45:87,2*n_original,TRUE),SEX=sample(c("F","M"),2*n_original,TRUE),RACE=sample(c("WHITE","ASIAN","BLACK OR AFRICAN AMERICAN"),2*n_original,TRUE),TRT01AN=rep(c(1,2,3,1,2),length.out=2*n_original),stringsAsFactors=FALSE)

# Expand each subject into the five physical-examination body systems.
systems <- data.frame(PARAM=c("General Appearance","Skin","Eyes","Ears / Nose / Throat","Head and Neck"),PARAMCD=c("GENAPP","SKIN","EYES","ENT","HEADNECK"),PARAMN=1:5,stringsAsFactors=FALSE)
adpe <- do.call(rbind,lapply(seq_len(nrow(adsl)),function(i){
  abnormal <- sample(seq_len(nrow(systems)),sample(0:1,1))
  result <- ifelse(seq_len(nrow(systems)) %in% abnormal,"ABNORMAL","NORMAL")
  data.frame(USUBJID=adsl$USUBJID[i],AGE=adsl$AGE[i],SEX=adsl$SEX[i],RACE=adsl$RACE[i],PEDTC=as.character(as.Date("2020-06-01")+sample(0:180,1)),ADY=sample(-30:-1,1),AVISIT="Baseline",AVISITN=0,PESTAT="",PECLSIG=ifelse(result=="ABNORMAL","Y",""),PARAM=systems$PARAM,PARAMCD=systems$PARAMCD,PARAMN=systems$PARAMN,PEORRES=result,AVALC=ifelse(result=="NORMAL","Normal","Abnormal"),ABLFL="Y",ANL01FL="Y",SAFFL="Y",TRT01AN=adsl$TRT01AN[i],stringsAsFactors=FALSE)
}))
stopifnot(nrow(adsl)==20,all(names(adpe)==toupper(names(adpe))))

# Helper functions for Excel and clinical RTF output are inserted below.

listing <- adpe[order(adpe$USUBJID,adpe$PARAMN),c("USUBJID","TRT01AN","PARAM","PEORRES","PECLSIG","AVISIT","PEDTC","AGE","SEX","RACE")]
names(listing) <- c("Subject","Treatment","Body System","Result","Clinically Significant","Visit","Assessment Date","Age","Sex","Race")
# Locate LibreOffice without requiring `soffice` to be on PATH.
find_soffice <- function() {
  paths <- c(Sys.which("soffice"), "/Applications/LibreOffice.app/Contents/MacOS/soffice", "/Applications/OpenOffice.app/Contents/MacOS/soffice", "/Users/dianhe/.cache/codex-runtimes/codex-primary-runtime/dependencies/bin/override/soffice")
  paths <- paths[nzchar(paths) & file.exists(paths)]
  if (!length(paths)) stop("LibreOffice was not found.")
  paths[1]
}

# Export standards-compliant XLSX data.
write_xlsx <- function(data, path) {
  csv <- tempfile(fileext=".csv")
  write.csv(data, csv, row.names=FALSE, na="", fileEncoding="UTF-8")
  xlsx <- file.path(tempdir(), sub("\\.csv$", ".xlsx", basename(csv)))
  if (file.exists(xlsx)) unlink(xlsx)
  status <- system2(find_soffice(), c("--headless", "--convert-to", "xlsx", "--outdir", shQuote(tempdir()), shQuote(csv)))
  if (status != 0 || !file.exists(xlsx)) stop("Unable to create Excel workbook.")
  if (file.exists(path)) unlink(path)
  if (!file.rename(xlsx, path)) stop("Unable to save Excel workbook.")
  unlink(csv)
}

# Create the clinical RTF listing using integer cell boundaries.
escape_rtf <- function(x) { x <- gsub("\\\\", "\\\\\\\\", as.character(x)); gsub("([{}])", "\\\\\\1", x) }
write_rtf <- function(data, path) {
  con <- file(path, "wb"); on.exit(close(con), add=TRUE)
  w <- function(...) writeLines(paste0(...), con, useBytes=TRUE)
  w("{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Arial;}}\\landscape\\paperw15840\\paperh12240\\margl600\\margr600\\margt500\\margb600")
  w("\\pard\\fs15 PILOT\\tab Confidential\\tab Page {\\field{\\*\\fldinst PAGE}}\\par\\pard\\qc\\b\\fs19 Listing 1. Physical Examination\\b0\\par\\pard\\qc\\fs15 Safety Population\\par\\par")
  n <- ncol(data)
  widths <- c(1500, 1200, 2200, 1300, 1700, 1400, 1500, 800, 700, 2340)
  stopifnot(length(widths) == n, sum(widths) == 14640)
  ends <- cumsum(widths)
  for (i in 0:nrow(data)) { v <- if(i==0) names(data) else as.character(data[i,]); b <- if(i==0) "\\clbrdrt\\brdrs\\brdrw15\\clbrdrb\\brdrs\\brdrw15" else if(i==nrow(data)) "\\clbrdrb\\brdrs\\brdrw15" else ""; w("\\trowd\\trleft0\\trgaph60",if(i==0)"\\trhdr" else "",paste0(b,"\\cellx",ends,collapse="")); for(j in seq_len(n)) w("\\intbl",if(j<=3)"\\ql" else "\\qc",if(i==0)"\\b" else "\\b0","\\fs14 ",escape_rtf(v[j]),"\\cell"); w("\\row") }
  w("\\pard\\ql\\fs12\\par Source: simulated data generated by this standalone program.\\par}")
}
write_rtf(listing,file.path(out_dir,paste0(stem,".rtf")))
write_xlsx(adpe,file.path(out_dir,paste0(stem,"_simulated_data.xlsx")))
message("Created ",stem,": original N=10; simulated N=20")
