---
title: "Linear mixed model MCMC"
output: html_document
date: '2024-09-05'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Linear mixed model in JAGS for random intercept

```{r}
library(R2jags)
# create dataset
library(nlme)
  snakes3=Orthodont
  snakes3$bw = rep(c(1:27),each=4) 
  names(snakes3)=c( "b_mass" ,"b_length","site"  ,"sex","bw" )

  snakes3=snakes3[sample(nrow(snakes3)*0.8  ), ]
  head(snakes3)
  table(snakes3$site)
  nrow(snakes3)
  
  plot(b_mass ~ b_length, col = site, data = snakes3)
  # snakes3 <- within(snakes3, sex <- relevel(sex, ref = "Female"))
  
  summary(lme(b_mass ~ b_length +  (sex), data = snakes3, random = ~ 1|site))
  # summary(lme(b_mass ~ b_length  , data = snakes3, random = ~ 1|site))
```


```{r}
  Nsites <- length(levels(as.factor(snakes3$site)))
  jagsdata_s3 <- with(snakes3, list(b_mass = b_mass, b_length = b_length, site = site, sex=sex,
                                    N = length(b_mass), Nsites = Nsites))
  
  # The JAGS model
    lm3_jags <- function(){
      # Likelihood:
      for (i in 1:N){
        b_mass[i] ~ dnorm(mu[i], tau) # tau is precision (1 / variance)
        mu[i] <- alpha + a[site[i]] + beta * b_length[i]+ gama*sex[i] # Random intercept for site
      }
      # Priors:
      alpha ~ dnorm(0, 0.01) # intercept
      
      sigma_a ~ dunif(0, 100) # standard deviation of random effect (variance between sites)
      tau_a <- 1 / (sigma_a * sigma_a) # convert to precision
      for (j in 1:Nsites){
        a[j] ~ dnorm(0, tau_a) # random intercept for each site
      }
      
      beta ~ dnorm(0, 0.01) # slope
      gama ~ dnorm(0, 0.01) # slope
      
      sigma ~ dunif(0, 100) # standard deviation of fixed effect (variance within sites)
      tau <- 1 / (sigma * sigma) # convert to precision
    }
  
    init_values <- function(){
      list(alpha = rnorm(1), sigma_a = runif(1), beta = rnorm(1), sigma = runif(1),gama=   rnorm(1) )
    }
    
    params <- c("alpha", "beta", "sigma", "sigma_a", "gama")
    
    fit_lm3 <- jags(data = jagsdata_s3, inits = init_values, parameters.to.save = params, model.file = lm3_jags,
                    n.chains = 3, n.iter = 20000, n.burnin = 5000, n.thin = 10, DIC = F)
  
    fit_lm3
```
### Linear mixed model in JAGS for random slope

`we suppose they are independent of random intercept and slope`

```{r}
   (lme(b_mass ~ b_length +  (sex), data = snakes3, random = ~ 1+sex|site))
    # summary(lme(b_mass ~ b_length  , data = snakes3, random = ~ 1|site))
    
    Nsites <- length(levels(as.factor(snakes3$site)))
    jagsdata_s3 <- with(snakes3, list(b_mass = b_mass, b_length = b_length, site = site, sex=sex,
                                      N = length(b_mass), Nsites = Nsites))
    
    # The JAGS model  
    
    lm3_jags <- function(){
      # Likelihood:
      for (i in 1:N){
        b_mass[i] ~ dnorm(mu[i], tau) # tau is precision (1 / variance)
        mu[i] <- (alpha + a[site[i]] )+ beta * b_length[i]+ (gama+g[site[i]]) *sex[i] # Random intercept for site
      }
      # Priors:
      alpha ~ dnorm(0, 0.01) # intercept
      
      
      sigma_a ~ dunif(0, 100) # standard deviation of random effect (variance between sites)
      tau_a <- 1 / (sigma_a * sigma_a) # convert to precision
      for (j in 1:Nsites){
        a[j] ~ dnorm(0, tau_a) # random intercept for each site
      }
      sigma_g ~ dunif(0, 100) # standard deviation of random effect (variance between sites)
      tau_g <- 1 / (sigma_g * sigma_g) # convert to precision
      for (j in 1:Nsites){
        g[j] ~ dnorm(0, tau_g) # random intercept for each site
      }
      
      beta ~ dnorm(0, 0.01) # slope
      gama ~ dnorm(0, 0.01) # slope
      
      sigma ~ dunif(0, 100) # standard deviation of fixed effect (variance within sites)
      tau <- 1 / (sigma * sigma) # convert to precision
    }
    
    init_values <- function(){
      list(alpha = rnorm(1), sigma_a = runif(1), sigma_g = runif(1),beta = rnorm(1), sigma = runif(1),gama=   rnorm(1) )
    }
    
    params <- c("alpha", "beta", "sigma", "sigma_a","sigma_g", "gama")
    
    fit_lm34 <- jags(data = jagsdata_s3, inits = init_values, parameters.to.save = params, model.file = lm3_jags,
                    n.chains = 3, n.iter = 20000, n.burnin = 5000, n.thin = 10, DIC = F)
    
    fit_lm34
```

**The results are a little different**


`we suppose they are not independent of random intercept and slope`

```{r}
    Nsites <- length(levels(as.factor(snakes3$site)))
    jagsdata_s3 <- with(snakes3, list(b_mass = b_mass, b_length = b_length, site = site, sex=sex,
                                      N = length(b_mass), Nsites = Nsites))
    
    # The JAGS model  
    
    lm3_jags <- function(){
      # Likelihood:
      for (i in 1:N){
        
        b_mass[i] ~ dnorm(mu[i], tau) # tau is precision (1 / variance)
        
        mu[i] <- (alpha + a[site[i]] )+ beta * b_length[i]+ (gama+g[site[i]]) *sex[i] # Random intercept for site
      }
      # Priors:
      alpha ~ dnorm(0, 0.01) # intercept
      
      
 for (j in 1:Nsites){
       ## random effects 
## mean is 0
b0[j,1] = 0   
b0[j,2] = 0
b[j,1:2] ~ dmnorm(b0[j,1:2],ISigma[,]) ## MV normal

 a[j] =b[j,1] 
 g[j]=b[j,2] 
 }

      #(3) Variance-covariance matrix
ISigma[1:2,1:2] ~dwish(R[,],3)
Sigma[1:2,1:2] = inverse(ISigma[,])
R[1,1] =1
R[1,2] =0
R[2,2] =1
R[2,1] =0


      beta ~ dnorm(0, 0.01) # slope
      gama ~ dnorm(0, 0.01) # slope
      
      sigma ~ dunif(0, 100) # standard deviation of fixed effect (variance within sites)
      tau <- 1 / (sigma * sigma) # convert to precision
    }
    
    init_values <- function(){
      list(alpha = rnorm(1), sigma_a = runif(1), sigma_g = runif(1),beta = rnorm(1), sigma = runif(1),gama=   rnorm(1) )
    }
    
    params <- c("alpha", "beta", "sigma", "Sigma", "gama")
    
    fit_lm35 <- jags(data = jagsdata_s3, inits = init_values, parameters.to.save = params, model.file = lm3_jags,
                    n.chains = 3, n.iter = 20000, n.burnin = 5000, n.thin = 10, DIC = F)
    
    fit_lm35
```

`similar results for the above scenarios`

### Join model for missing data
```{r}

    Nsites <- length(levels(as.factor(snakes3$site)))
    jagsdata_s3 <- with(snakes3, list(b_mass = b_mass, b_length = b_length, site = site, sex=sex,
                                      N = length(b_mass), Nsites = Nsites,bw=bw))
    
    # The JAGS model  
    
    lm3_jags <- function(){
      # Likelihood:
      for (i in 1:N){
        
        b_mass[i] ~ dnorm(mu[i], tau) # tau is precision (1 / variance)
        
        mu[i] <- (alpha + a[site[i]] )+ beta * b_length[i]+ (gama+g[site[i]]) *sex[i] # Random intercept for site
        
        ## linear regression model 
bw[i] ~ dnorm(m[i],1)
m[i] = bb[1] + bb[2]*a[site[i]] + bb[3]*g[site[i]]
      }
      
      # Priors:
      alpha ~ dnorm(0, 0.01) # intercept
        
      #(1) Coefficients
for (ll in 1:3) { bb[ll] ~ dnorm(0, .01) }
      
 for (j in 1:Nsites){
       ## random effects 
## mean is 0
b0[j,1] = 0   
b0[j,2] = 0
b[j,1:2] ~ dmnorm(b0[j,1:2],ISigma[,]) ## MV normal

 a[j] =b[j,1] 
 g[j]=b[j,2] 
 }

      #(3) Variance-covariance matrix
ISigma[1:2,1:2] ~dwish(R[,],3)
Sigma[1:2,1:2] = inverse(ISigma[,])
R[1,1] =1
R[1,2] =0
R[2,2] =1
R[2,1] =0


      beta ~ dnorm(0, 0.01) # slope
      gama ~ dnorm(0, 0.01) # slope
      
      sigma ~ dunif(0, 100) # standard deviation of fixed effect (variance within sites)
      tau <- 1 / (sigma * sigma) # convert to precision
    }
    
    init_values <- function(){
      list(alpha = rnorm(1), sigma_a = runif(1), sigma_g = runif(1),beta = rnorm(1), sigma = runif(1),gama=   rnorm(1) ,bb= rnorm(3))
    }
    
    params <- c("alpha", "beta", "sigma", "Sigma", "gama","bb","a","g")
    
    fit_lm35 <- jags(data = jagsdata_s3, inits = init_values, parameters.to.save = params, model.file = lm3_jags,
                    n.chains = 3, n.iter = 20000, n.burnin = 5000, n.thin = 10, DIC = F)
    
    fit_lm35
```

```{r}
table(snakes3$site)
```

 

