# Listing 1: Electrocardiogram Measurements
# Standalone program rebuilt from the ADEG source-data structure in Listings- ECG.docx.

set.seed(4401)

arg <- grep("^--file=", commandArgs(), value=TRUE)
out_dir <- if (length(arg)) dirname(normalizePath(gsub("~[+]~", " ", sub("^--file=", "", arg[1])), mustWork=TRUE)) else getwd()
stem <- "01_ecg_listing"

# Simulate 20 subjects (twice the 10-subject source-style example).
n_original <- 10L
subjects <- sprintf("PILOT-%04d", 1001:(1000 + 2 * n_original))
adsl <- data.frame(
  USUBJID = subjects,
  TRT01A = rep(c("Treatment 1", "Treatment 2"), each=n_original),
  TRT01AN = rep(1:2, each=n_original),
  SITEID = sample(c("101", "102", "103"), 2*n_original, TRUE),
  AGE = sample(45:85, 2*n_original, TRUE),
  SEX = sample(c("F", "M"), 2*n_original, TRUE),
  ARACE = sample(c("ASIAN", "WHITE", "BLACK OR AFRICAN AMERICAN"), 2*n_original, TRUE),
  WEIGHTBL = round(rnorm(2*n_original, 75, 14), 1),
  SAFFL = "Y", stringsAsFactors=FALSE
)

# Expand each subject into four ECG parameters at screening, baseline and Week 20.
parameters <- data.frame(PARAMCD=c("PR", "QRS", "QT", "QTCF"), PARAM=c("PR Interval (msec)", "QRS Interval (msec)", "QT Interval (msec)", "QTcF Interval (msec)"), CENTER=c(175, 95, 410, 425))
visits <- data.frame(AVISITN=c(-5,0,20), AVISIT=c("Screening", "Baseline", "Week 20"), ADY=c(-34,1,141), stringsAsFactors=FALSE)
adeg <- do.call(rbind, lapply(seq_len(nrow(adsl)), function(i) {
  do.call(rbind, lapply(seq_len(nrow(parameters)), function(p) {
    base <- round(rnorm(1, parameters$CENTER[p], 12))
    vals <- round(base + c(rnorm(1, 0, 8), 0, rnorm(1, 0, 9)))
    data.frame(USUBJID=adsl$USUBJID[i], PARAMCD=parameters$PARAMCD[p], PARAM=parameters$PARAM[p], AVISITN=visits$AVISITN, AVISIT=visits$AVISIT, ADT=visits$ADY, ADY=visits$ADY, AVAL=vals, BASE=base, CHG=vals-base, VISIT=visits$AVISIT, TRT01A=adsl$TRT01A[i], TRT01AN=adsl$TRT01AN[i], SITEID=adsl$SITEID[i], AGE=adsl$AGE[i], SEX=adsl$SEX[i], ARACE=adsl$ARACE[i], WEIGHTBL=adsl$WEIGHTBL[i], SAFFL="Y", stringsAsFactors=FALSE)
  }))
}))
stopifnot(nrow(adsl)==20, all(names(adeg)==toupper(names(adeg))))

# Locate LibreOffice without requiring `soffice` to be on PATH.
find_soffice <- function() {
  paths <- c(Sys.which("soffice"), "/Applications/LibreOffice.app/Contents/MacOS/soffice", "/Applications/OpenOffice.app/Contents/MacOS/soffice", "/Users/dianhe/.cache/codex-runtimes/codex-primary-runtime/dependencies/bin/override/soffice")
  paths <- paths[nzchar(paths) & file.exists(paths)]
  if (!length(paths)) stop("LibreOffice was not found.")
  paths[1]
}

# Export standards-compliant XLSX data.
write_xlsx <- function(data, path) {
  csv <- tempfile(fileext=".csv")
  write.csv(data, csv, row.names=FALSE, na="", fileEncoding="UTF-8")
  xlsx <- file.path(tempdir(), sub("\\.csv$", ".xlsx", basename(csv)))
  if (file.exists(xlsx)) unlink(xlsx)
  status <- system2(find_soffice(), c("--headless", "--convert-to", "xlsx", "--outdir", shQuote(tempdir()), shQuote(csv)))
  if (status != 0 || !file.exists(xlsx)) stop("Unable to create Excel workbook.")
  if (file.exists(path)) unlink(path)
  if (!file.rename(xlsx, path)) stop("Unable to save Excel workbook.")
  unlink(csv)
}

# Create the clinical RTF listing using integer cell boundaries.
escape_rtf <- function(x) { x <- gsub("\\\\", "\\\\\\\\", as.character(x)); gsub("([{}])", "\\\\\\1", x) }
write_rtf <- function(data, path) {
  con <- file(path, "wb"); on.exit(close(con), add=TRUE)
  w <- function(...) writeLines(paste0(...), con, useBytes=TRUE)
  w("{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Arial;}}\\landscape\\paperw15840\\paperh12240\\margl600\\margr600\\margt500\\margb600")
  w("\\pard\\fs15 PILOT\\tab Confidential\\tab Page {\\field{\\*\\fldinst PAGE}}\\par\\pard\\qc\\b\\fs19 Listing 1. Electrocardiogram Measurements\\b0\\par\\pard\\qc\\fs15 Safety Population\\par\\par")
  n <- ncol(data)
  widths <- c(1900, 1900, 2200, 1900, 1700, 1600, 1600, 970, 870)
  stopifnot(length(widths) == n, sum(widths) == 14640)
  ends <- cumsum(widths)
  for (i in 0:nrow(data)) { v <- if(i==0) names(data) else as.character(data[i,]); b <- if(i==0) "\\clbrdrt\\brdrs\\brdrw15\\clbrdrb\\brdrs\\brdrw15" else if(i==nrow(data)) "\\clbrdrb\\brdrs\\brdrw15" else ""; w("\\trowd\\trleft0\\trgaph60",if(i==0)"\\trhdr" else "",paste0(b,"\\cellx",ends,collapse="")); for(j in seq_len(n)) w("\\intbl",if(j<=3)"\\ql" else "\\qc",if(i==0)"\\b" else "\\b0","\\fs14 ",escape_rtf(v[j]),"\\cell"); w("\\row") }
  w("\\pard\\ql\\fs12\\par Source: simulated data generated by this standalone program.\\par}")
}

listing <- adeg[, c("USUBJID","TRT01A","PARAMCD","AVISIT","AVAL","BASE","CHG","AGE","SEX")]
names(listing) <- c("Subject","Treatment","Parameter","Visit","Value (msec)","Baseline","Change","Age","Sex")

# Suppress consecutive repeated text in the first three hierarchical columns.
if (nrow(listing) > 0L) {
  new_subject <- c(TRUE, listing$Subject[-1] != listing$Subject[-nrow(listing)])
  new_treatment <- new_subject | c(TRUE, listing$Treatment[-1] != listing$Treatment[-nrow(listing)])
  new_parameter <- new_treatment | c(TRUE, listing$Parameter[-1] != listing$Parameter[-nrow(listing)])

  listing$Subject[!new_subject] <- ""
  listing$Treatment[!new_treatment] <- ""
  listing$Parameter[!new_parameter] <- ""
}

write_xlsx(adeg, file.path(out_dir, paste0(stem,"_simulated_data.xlsx")))
write_rtf(listing, file.path(out_dir, paste0(stem,".rtf")))
message("Created ", stem, ": original N=10; simulated N=20")
