-- GENERATED by scripts/build_navigation.R; do not edit.
return {
  ["Clinical Trial SAP Template"] = {youtube={}, pdf={}, downloads={{title="SAP outline",file="files/sap-outline.txt"}}},
  ["Introduction to ADaM"] = {youtube={}, pdf={}, downloads={}},
  ["Introduction to Real-World Evidence"] = {youtube={}, pdf={}, downloads={}},
  ["Kaplan-Meier Survival Analysis in R"] = {youtube={"bM7LSQ1tQnU"}, pdf={{title="Kaplan-Meier Notes",file="files/kaplan-meier-notes.pdf"}}, downloads={{title="R example",file="files/km-analysis.R"},{title="Example dataset",file="files/km-data.csv"},{title="PDF notes",file="files/kaplan-meier-notes.pdf"}}},
  ["Introduction to Parallel Group Trials"] = {youtube={}, pdf={}, downloads={}},
}
