---
title: "Manual simulating data for linear mix model"
output: html_document
date: '2023-05-12'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

[Reference] (https://stats.stackexchange.com/questions/11233/how-to-simulate-data-based-on-a-linear-mixed-model-fit-object-in-r)

Manual simulating data for linear mix model with the random intercepts
```{r}
library(nlme)
fm2 <- lme(distance ~ age + Sex, data = Orthodont, random = ~ 1) 

simfun <- function(n) {
  # n is the number of subjects, total rows will be 4*n
  # n=10
  # sig.b0 is the st. dev. of the random intercepts
  # it might be easier to just copy from the output
  sig.b0 <- exp(unlist(fm2$modelStruct$reStruct))*fm2$sigma
  
  b0 <- rnorm(n, 0, sig.b0)  #random intercepts
  
  sex <- rbinom(n, 1, 0.5)  # assign sex at random
  
  fe <- fixef(fm2)  #fixed coefficients
  
  my.df <- data.frame( Subject=as.factor(rep(1:n, each=4)), 
                       int = fe[1] + rep(b0, each=4), 
                       Sex=rep(sex,each=4), age=rep( c(8,10,12,14), n ) )       #create sex and age
  
  my.df$distance <- my.df$int + fe[2] * my.df$age + 
    fe[3]*my.df$Sex + rnorm(n*4, 0, fm2$sigma) #generate distance
  
  my.df$int <- NULL
  my.df$Sex <- factor( my.df$Sex, levels=0:1,
                       labels=c('Male','Female') ) #label sex
  my.df
}

Orthodont2 <- simfun(10)

```

Compare simulated data and original data
```{r}
summary(lme(distance ~ age +  (Sex), data = Orthodont, random = ~ 1|Subject))

summary(lme(distance ~ age +  (Sex), data = Orthodont2, random = ~ 1|Subject ))
```

Manual bootstrap sampling
```{r}
###################

# set the number of participants in your big simulated study

nits=300 
# get the unique participants in the small study

sub=unique(Orthodont$Subject)
# sample the unique participants randomly with replacement

subs=sample(sub,nits,rep=T)
# make an empty data frame

df=Orthodont[-(1:dim(Orthodont)[1]),]  #empty data table
# loop through the sample size and bind it together.

for( i in 1:nits) {  
  df=rbind(df,Orthodont[which(Orthodont$Subject==subs[i]),])
}

#  nrow(df)
# [1] 1200
```

Using simulate function to sample automatically (and aggregate the statistics )
```{r}
# simple simulation based on multi variates distribution 
# general linear
x <- 1:5
mod1 <- lm(c(1:3, 7, 6) ~ x)
S2 <- simulate(mod1, nsim = 200, seed = 123)
rowMeans(S2) 
fitted(mod1)

# generized linear
x2 <- sort(runif(100))
yb2 <- rbinom(100, prob = plogis(2*(x2-1)), size = 1)
yb2 <- factor(1 + yb2, labels = c("failure", "success"))
modb2 <- glm(yb2 ~ x2, family = binomial)
S4 <- simulate(modb2, nsim = 2)
```

