#!/usr/bin/env Rscript
suppressPackageStartupMessages(library(yaml))
source("scripts/site_helpers.R")

nav <- yaml::read_yaml("config/navigation.yml")$navigation
posts <- post_records(FALSE)
sections <- Filter(function(x) !is.null(x$slug), nav)
section_render_paths <- vapply(sections, function(x) paste0('    - "_generated/', x$slug, '/index.qmd"'), "")

navbar <- unlist(lapply(nav, function(item) {
  href <- item$href %||% paste0("_generated/", item$slug, "/index.qmd")
  c(paste0("      - text: ", q(item$title)), paste0("        href: ", href))
}))

draft_paths <- vapply(post_records(TRUE), function(x) if (identical(x$status %||% "published", "draft")) paste0('    - "!', x$path, '"') else NA_character_, "")
draft_paths <- draft_paths[!is.na(draft_paths)]
quarto <- c(
  "# GENERATED by scripts/build_navigation.R from config/navigation.yml; do not edit.",
  "validate-yaml: false",
  "project:", "  type: website", "  output-dir: _site", "  pre-render: Rscript scripts/build_navigation.R", "  post-render: Rscript scripts/check_render.R",
  "  render:", "    - \"index.qmd\"", "    - \"404.qmd\"", "    - \"posts/*/index.qmd\"", section_render_paths, draft_paths,
  "  resources:", "    - \"posts/*/files/**\"", "    - \"posts/*/images/**\"",
  "", "website:", "  title: \"Clinical Statistics Notes\"", "  description: \"Practical knowledge for clinical research, data, and statistics.\"",
  "  site-url: \"https://daniel-355.github.io/clinical-statistics-site\"", "  favicon: assets/favicon/favicon.svg", "  search: true", "  page-navigation: true",
  "  navbar:", "    logo: assets/logo/mark.svg", "    background: white", "    foreground: dark", "    pinned: true", "    right:", navbar,
  "  page-footer:", "    left: \"Clinical Statistics Notes\"", "    right: \"Built with Quarto · Content reviewed before use\"",
  "", "format:", "  html:", "    theme: cosmo", "    css: styles.css", "    toc: true", "    toc-location: right", "    code-copy: true", "    smooth-scroll: true", "    link-external-newwindow: true", "    filters:", "      - filters/post-layout.lua",
  "", "execute:", "  freeze: auto"
)
write_utf8(quarto, "_quarto.yml")

lua_string <- function(x) paste0('"', gsub('"', '\\\"', gsub("\\\\", "\\\\\\\\", x)), '"')
lua_items <- function(items) {
  if (!length(items)) return("{}")
  paste0("{", paste(vapply(items, function(item) paste0("{title=", lua_string(item$title %||% "Download"), ",file=", lua_string(item$file %||% ""), "}"), ""), collapse = ","), "}")
}
manifest <- c("-- GENERATED by scripts/build_navigation.R; do not edit.", "return {")
for (p in posts) manifest <- c(manifest, paste0("  [", lua_string(p$title), "] = {youtube=", paste0("{", paste(vapply(p$youtube %||% list(), function(x) lua_string(as.character(x)), ""), collapse = ","), "}"), ", pdf=", lua_items(p$pdf %||% list()), ", downloads=", lua_items(p$downloads %||% list()), "},"))
manifest <- c(manifest, "}")
write_utf8(manifest, "_generated/post-media.lua")

for (section in sections) {
  section_posts <- Filter(function(p) identical(p$section, section$title), posts)
  sidebar <- unlist(lapply(section$children, function(cat) {
    id <- slugify(cat$title)
    paste0('<a href="#', id, '">', cat$title, '</a>')
  }))
  blocks <- unlist(lapply(section$children, function(cat) {
    cat_posts <- Filter(function(p) identical(p$category, cat$title), section_posts)
    topics <- unique(vapply(cat_posts, function(p) p$topic %||% "General", ""))
    topic_html <- if (!length(topics)) {
      '<p class="text-muted">No published notes yet.</p>'
    } else unlist(lapply(topics, function(topic) {
      these <- Filter(function(p) identical(p$topic %||% "General", topic), cat_posts)
      links <- vapply(these, function(p) paste0('<li><a href="../../', p$path, '">', p$title, '</a></li>'), "")
      c('<div class="topic-group">', paste0("<h3>", topic, "</h3>"), "<ul>", links, "</ul>", "</div>")
    }))
    c(paste0('<section class="category-block" id="', slugify(cat$title), '">'), paste0("<h2>", cat$title, "</h2>"), topic_html, "</section>")
  }))
  page <- c("---", paste0("title: ", q(section$title)), paste0("description: ", q(paste("Notes and resources for", section$title))), "toc: false", "---", "",
            '<div class="section-layout">', '<nav class="section-nav" aria-label="Categories">', '<p class="nav-title">In this section</p>', sidebar, "</nav>", "<main>", blocks, "</main>", "</div>")
  write_utf8(page, file.path("_generated", section$slug, "index.qmd"))
}

published <- posts[order(vapply(posts, function(p) as.character(p$date %||% "1900-01-01"), ""), decreasing = TRUE)]
featured <- Filter(function(p) isTRUE(p$featured), published)
with_downloads <- Filter(function(p) length(p$downloads %||% list()) > 0, published)
topic_cards <- unlist(lapply(Filter(function(x) !x$slug %in% "about", sections), function(s) c(
  paste0('<a class="topic-card" href="_generated/', s$slug, '/index.qmd">'), paste0("<strong>", s$title, "</strong>"), paste0("<span>", length(s$children), " subject areas</span>"), "</a>"
)))
post_rows <- function(items, limit = 5) {
  if (!length(items)) return('<p class="text-muted">No published posts yet.</p>')
  items <- head(items, limit)
  vapply(items, function(p) paste0('<div class="post-row"><div><a href="', p$path, '">', p$title, '</a><div class="post-meta">', p$category, " · ", p$topic, '</div></div><time datetime="', p$date, '">', p$date, '</time></div>'), "")
}
download_rows <- function(items, limit = 4) {
  if (!length(items)) return('<p class="text-muted">No downloads yet.</p>')
  unlist(lapply(head(items, limit), function(p) {
    d <- p$downloads[[1]]
    paste0('<div class="download-row"><div><a href="', p$path, '">', p$title, '</a><div class="post-meta">', d$title, '</div></div><a href="', dirname(p$path), '/', d$file, '" download>Download</a></div>')
  }))
}
home <- c(
  '<header class="hero"><div class="hero-inner">', '<p class="eyebrow">Clinical research knowledge base</p>', '<h1>Evidence, methods,<br>and the work between.</h1>', '<p>Practical notes for designing studies, managing clinical data, and making statistical decisions that can be explained and reproduced.</p>', '</div></header>',
  '<div class="home-shell">', '<section class="home-section" id="topics"><h2>Main topics</h2><p>Browse the knowledge base by discipline.</p><div class="topic-grid">', topic_cards, '</div></section>',
  '<section class="home-section" id="featured"><h2>Featured</h2><div class="post-list">', post_rows(featured, 3), '</div></section>',
  '<section class="home-section" id="downloads"><h2>Downloads</h2><div class="download-list">', download_rows(with_downloads, 4), '</div></section>',
  '<section class="home-section" id="latest"><h2>Latest posts</h2><div class="post-list">', post_rows(published, 5), '</div></section>', '</div>'
)
write_utf8(home, "_generated/home.qmd")
message("Generated navigation and listings for ", length(posts), " published posts.")
