# Listing 1: Protocol Deviations
# Standalone program rebuilt from the ADDV source-data structure.

set.seed(4701)

arg <- grep("^--file=", commandArgs(), value=TRUE)
out_dir <- if (length(arg)) dirname(normalizePath(gsub("~[+]~", " ", sub("^--file=", "", arg[1])), mustWork=TRUE)) else getwd()
stem <- "01_protocol_deviations_listing"

# Simulate 40 deviation records, twice the 20-record source-style example.
n_original <- 20L
subjects <- sprintf("PILOT-%04d", sample(1001:1020, 2*n_original, replace=TRUE))
addv <- data.frame(
  USUBJID=subjects,
  PARCAT1="PROTOCOL DEVIATIONS LOG",
  DVDECOD=sample(c("PD1","PD3","PD4"),2*n_original,TRUE,prob=c(.2,.7,.1)),
  DVSUBCOD=sample(c("PD3_2","EX07","EX12","EX16","NA"),2*n_original,TRUE),
  TRTEDY=sample(c(NA,31,34,69,125,225,365,417,727),2*n_original,TRUE),
  SITEID=sample(c("002","003","004","007"),2*n_original,TRUE),
  RANDFL="Y",
  TRT01P=sample(c("Arm A","Arm B"),2*n_original,TRUE),
  stringsAsFactors=FALSE
)
addv$SITENAM <- paste("Site", addv$SITEID)
addv$TRT01PN <- ifelse(addv$TRT01P=="Arm A",1,2)
stopifnot(nrow(addv)==40,all(names(addv)==toupper(names(addv))))

# Helper functions for Excel and clinical RTF output are inserted below.

# Locate LibreOffice without requiring `soffice` to be on PATH.
find_soffice <- function() {
  paths <- c(Sys.which("soffice"), "/Applications/LibreOffice.app/Contents/MacOS/soffice", "/Applications/OpenOffice.app/Contents/MacOS/soffice", "/Users/dianhe/.cache/codex-runtimes/codex-primary-runtime/dependencies/bin/override/soffice")
  paths <- paths[nzchar(paths) & file.exists(paths)]
  if (!length(paths)) stop("LibreOffice was not found.")
  paths[1]
}

# Export standards-compliant XLSX data.
write_xlsx <- function(data, path) {
  csv <- tempfile(fileext=".csv")
  write.csv(data, csv, row.names=FALSE, na="", fileEncoding="UTF-8")
  xlsx <- file.path(tempdir(), sub("\\.csv$", ".xlsx", basename(csv)))
  if (file.exists(xlsx)) unlink(xlsx)
  status <- system2(find_soffice(), c("--headless", "--convert-to", "xlsx", "--outdir", shQuote(tempdir()), shQuote(csv)))
  if (status != 0 || !file.exists(xlsx)) stop("Unable to create Excel workbook.")
  if (file.exists(path)) unlink(path)
  if (!file.rename(xlsx, path)) stop("Unable to save Excel workbook.")
  unlink(csv)
}

# Create the clinical RTF listing using integer cell boundaries.
escape_rtf <- function(x) { x <- gsub("\\\\", "\\\\\\\\", as.character(x)); gsub("([{}])", "\\\\\\1", x) }
write_rtf <- function(data, path) {
  con <- file(path, "wb"); on.exit(close(con), add=TRUE)
  w <- function(...) writeLines(paste0(...), con, useBytes=TRUE)
  w("{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Arial;}}\\landscape\\paperw15840\\paperh12240\\margl600\\margr600\\margt500\\margb600")
  w("\\pard\\fs15 PILOT\\tab Confidential\\tab Page {\\field{\\*\\fldinst PAGE}}\\par\\pard\\qc\\b\\fs19 Listing 1. Protocol Deviations\\b0\\par\\pard\\qc\\fs15 Safety Population\\par\\par")
  n <- ncol(data)
  widths <- c(1700, 1600, 900, 1800, 3000, 2500, 1600, 1540)
  stopifnot(length(widths) == n, sum(widths) == 14640)
  ends <- cumsum(widths)
  for (i in 0:nrow(data)) { v <- if(i==0) names(data) else as.character(data[i,]); b <- if(i==0) "\\clbrdrt\\brdrs\\brdrw15\\clbrdrb\\brdrs\\brdrw15" else if(i==nrow(data)) "\\clbrdrb\\brdrs\\brdrw15" else ""; w("\\trowd\\trleft0\\trgaph60",if(i==0)"\\trhdr" else "",paste0(b,"\\cellx",ends,collapse="")); for(j in seq_len(n)) w("\\intbl",if(j<=3)"\\ql" else "\\qc",if(i==0)"\\b" else "\\b0","\\fs15 ",escape_rtf(v[j]),"\\cell"); w("\\row") }
  w("\\pard\\ql\\fs12\\par Source: simulated data generated by this standalone program.\\par}")
}
listing <- addv[order(addv$USUBJID,addv$TRTEDY),c("USUBJID","TRT01P","SITEID","SITENAM","DVDECOD","DVSUBCOD","TRTEDY","RANDFL")]
names(listing) <- c("Subject","Treatment","Site","Site Name","Deviation Code","Subcode","Treatment Day","Randomized")
write_xlsx(addv,file.path(out_dir,paste0(stem,"_simulated_data.xlsx")))
write_rtf(listing,file.path(out_dir,paste0(stem,".rtf")))
message("Created ",stem,": original N=20; simulated N=40")
