---
title: "How to use subscripts/superscripts for a figure"
output: html_document
date: '2023-05-08'
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## How to use subscripts/superscripts 

```{r}
# first plot I would like to have a subscript 1 and for the scond one a subscript 2

# One solution is to use bquote(). Use .() within bquote to get the value of objects or expressions.

plotf = function(title=expression("Test"~a )){
  plot(cars)
  title(title)
}

foo = expression(a[1], a^-2)
layout(matrix(1:2, nrow=1))

for(i in 1:2){
  plotf(title=bquote("Test"~.(foo[[i]]) ))  #bquote() to utilize the iteration
}
```

```{r}
# using astrisk instead of tilde
for(i in 1:2){
  plotf(title=bquote("Test"*a[.(i)]) )
}
```
Using two datasets
```{r}
# graph using two datasets
library(tidyverse)
data1=mtcars %>% filter(cyl>7)
data2=mtcars %>% filter(cyl<7)

ggplot() +
  geom_point(data = data1, aes(x=hp, y=disp),color="gray",size=1)+
  geom_line(data = data2, aes(x=hp, y=disp ) )   # must include argument label "data"
```

Convert a Vector to String and back
```{r}
#create vector
x <- c("Andy", "Bernard", "Caleb", "Dan", "Eric", "Frank", "Greg")

#convert vector to string
new_string <- toString(x)

#view string
new_string

#create vector
x <- c("Andy", "Bernard", "Caleb", "Dan", "Eric", "Frank", "Greg")

#convert vector to string
new_string <- paste(x, collapse = " ")

#view string
new_string
```

Convert string to vector
```{r}
# R convert string to vector
string1 <- "This   is my string"
strsplit(string1, "\\s+")[[1]]

string1 <- "This is my string"
scan(text = string1, what = "")
```



